.PHONY: test test2 test3 test4

test:
	corebuild -build-dir test test.native

test-clean:
	corebuild -build-dir test -clean

test2:
	corebuild -build-dir test2 -pkg core_bench test2.native

test2-clean:
	corebuild -build-dir test2 -clean

test3:
	corebuild -build-dir test3 -pkg core_bench test3.native

test3-clean:
	corebuild -build-dir test3 -clean

test4:
	corebuild -build-dir test4 -pkg core_bench test4.native

test4-clean:
	corebuild -build-dir test4 -clean