.PHONY: test test2 test3

test:
	corebuild -build-dir test test.native

test-clean:
	corebuild -build-dir test -clean

test2:
	corebuild -build-dir test2 -pkg core_bench test2.native

test2-clean:
	corebuild -build-dir test2 -clean

test3:
	corebuild -build-dir test3 -pkg core_bench test3.native

test3-clean:
	corebuild -build-dir test3 -clean